export const GLOSSARY: Record<string, string> = {
  ROAE: 'Retorno sobre Patrimônio Líquido Médio (anualizado). Mede a rentabilidade do banco em relação ao capital dos acionistas.',
  ROAA: 'Retorno sobre Ativos Médios (anualizado). Mede a eficiência do banco em gerar lucro com o total de ativos.',
  NIM: 'Net Interest Margin — Margem Financeira com Clientes (anualizada). Diferença entre o que o banco cobra em empréstimos e paga em captações.',
  NPL: 'Non-Performing Loans — Percentual da carteira com atraso acima de 90 dias. Indicador de qualidade de crédito.',
  Basileia: 'Índice de Adequação de Capital (BIS III). Relação entre Patrimônio de Referência e ativos ponderados pelo risco. Mínimo regulatório: 8%.',
  CET1: 'Common Equity Tier 1 — Capital de maior qualidade (ações ordinárias + lucros retidos). Mínimo regulatório: 4,5%.',
  'Nível I': 'Capital de Nível I = CET1 + AT1 (instrumentos híbridos). Absorve perdas sem liquidar o banco.',
  IE: 'Índice de Eficiência — Relação entre despesas operacionais e receitas totais. Quanto menor, mais eficiente.',
  PDD: 'Provisão para Devedores Duvidosos — Reserva constituída para cobrir perdas esperadas com inadimplência.',
  LTM: 'Last Twelve Months — Acumulado dos últimos 12 meses. Suaviza sazonalidade e facilita comparações.',
  DLSP: 'Dívida Líquida do Setor Público — Dívida bruta do governo menos os ativos financeiros. Expressa em % do PIB.',
  Spread: 'Diferença entre a taxa cobrada nos empréstimos e o custo de captação do banco. Principal driver da margem financeira.',
  Inadimplência: 'Percentual da carteira de crédito com atraso acima de 90 dias (critério Bacen).',
  'IBC-Br': 'Índice de Atividade Econômica do Banco Central — proxy mensal do PIB, usado como antecipador do crescimento.',
  Selic: 'Taxa básica de juros da economia brasileira, definida pelo Copom (Bacen) a cada 45 dias.',
  IPCA: 'Índice Nacional de Preços ao Consumidor Amplo — inflação oficial do Brasil, medida pelo IBGE.',
  'IGP-M': 'Índice Geral de Preços ao Mercado (FGV). Inclui preços no atacado, consumidor e construção civil. Usado em contratos de aluguel.',
  'Resultado primário': 'Diferença entre receitas e despesas do governo, excluindo juros da dívida. Positivo = superávit primário.',
  'Resultado nominal': 'Resultado primário menos os juros da dívida pública. Indica a variação real do endividamento do governo.',
  MPMEs: 'Micro, Pequenas e Médias Empresas. Segmento com maior spread bancário e inadimplência que grandes corporações.',
}
